#if !defined(MATERIAL_IDS_INCLUDE)
#define MATERIAL_IDS_INCLUDE
// This file was automatically generated by block_wrangler


bool materialIsWater(int id) {
	return id == 10008;
}


bool materialIsPlant(int id) {
	return id == 10001 || id == 10002 || id == 10004 || id == 10005 || id == 10006 || id == 10007;
}


struct Sway {int value;};
const Sway Sway_NONE = Sway(0);
const Sway Sway_UPPER = Sway(1);
const Sway Sway_LOWER = Sway(2);
const Sway Sway_HANGING = Sway(3);
const Sway Sway_FLOATING = Sway(4);
const Sway Sway_FULL = Sway(5);
Sway materialSwayType(int id) {
	if (id == 10006)
		return Sway_UPPER;
	if (id == 10005)
		return Sway_LOWER;
	if (id == 10003 || id == 10004)
		return Sway_HANGING;
	if (id == 10002)
		return Sway_FLOATING;
	if (id == 10001)
		return Sway_FULL;
	return Sway_NONE;
}


#endif // MATERIAL_IDS_INCLUDE