#if !defined(MATERIAL_IDS_INCLUDE)
#define MATERIAL_IDS_INCLUDE
// This file was automatically generated by block_wrangler


bool water(int id) {
	return id == 1001;
}


#endif // MATERIAL_IDS_INCLUDE