#version 430
// Generated by glsl-transformer
in vec4 direction_vert_out;
layout(location = 0) out vec4 position_frag_out;
layout(location = 1) out vec4 normal_frag_out;
layout(location = 2) out vec4 direct_frag_out;
layout(location = 3) out vec4 direct_soft_frag_out;
layout(location = 4) out vec4 handheld_frag_out;
struct Frag {
	vec4 direct;
	vec4 direct_soft;
};
uniform int frameCounter, frameTime;
uniform float frameTimeCounter, rainStrength, shadowFade, viewWidth, viewHeight;
uniform sampler2D depthtex0, noisetex;
uniform mat4 gbufferProjectionInverse, gbufferModelViewInverse, shadowProjection, shadowModelView;
uniform vec3 cameraPosition, eyePosition;
const int ph_block_size = 16;
const int ph_int_size = 4;
const int ph_schematic_size = ph_int_size * (ph_block_size * ph_block_size * ph_block_size);
const int ph_byte_size = ph_int_size + ph_int_size + ph_schematic_size;
layout(std430) restrict readonly buffer root_uniform { int root_array[32768]; };
layout(std430) restrict readonly buffer cb_block { int cb_array[]; };
layout(std430) restrict readonly buffer light_registry_block { int light_registry_array[]; };
const int light_size = 3;
layout(std140) uniform lights_uniform { vec4 lights_array[1000 * light_size]; };
uniform bool left_handed;
uniform bool light_reload;
uniform int light_time;
uniform int mask;
uniform int ph_light_count;
uniform mat4 direction_transformation_matrix_in;
uniform mat4 modelview_projection;
uniform mat4 previous_modelview_projection;
uniform vec3 rt_camera_position;
uniform vec3 handheld_color;
uniform vec3 previous_world_camera_position;
uniform vec3 world_camera_position;
uniform vec3 world_max_voxel;
uniform vec3 world_min_voxel;
uniform vec3 world_offset;
uniform layout(r32ui) uimage3D gi_x;
uniform layout(r32ui) uimage3D gi_y;
uniform layout(r32ui) uimage3D gi_z;
uniform layout(r32ui) uimage3D gi_w;
uniform layout(r32ui) uimage3D gi_d;
uniform sampler2D prev_radiosity_position;
uniform sampler2D prev_radiosity_normal;
uniform sampler2D prev_radiosity_direct;
uniform sampler2D prev_radiosity_direct_soft;
uniform sampler2D prev_radiosity_handheld;
uniform sampler2D radiosity_position;
uniform sampler2D radiosity_normal;
uniform sampler2D radiosity_direct;
uniform sampler2D radiosity_direct_soft;
uniform sampler2D radiosity_handheld;
struct RayJob {
	vec3 origin;
	vec3 direction;
	vec3 result_position;
	vec3 result_normal;
	vec3 result_color;
	bool result_hit;
};
struct Light {
	int blockId;
	vec3 position;
	vec3 color;
	float intensity;
	vec2 attenuation;
	float falloff;
	float block_radius;
};
ivec2 ires = textureSize(radiosity_position, 0);
ivec2 indirect_res = imageSize(gi_x).xy;
const vec3 NULL = vec3(424242.424242f);
int exposure_clear_index = 2 * ((frameCounter + 0) % 3);
int exposure_read_index = 2 * ((frameCounter + 1) % 3);
int exposure_write_index = 2 * ((frameCounter + 2) % 3);
int indirect_read_index = frameCounter & 1;
int indirect_write_index = indirect_read_index ^ 1;
vec2 reprojectf(mat4 mvp_matrix, vec3 world_position, vec2 viewSize, vec2 jitter);
void get_key(vec3 world_pos, vec3 normal, vec3 world_camera_pos, inout ivec3 key, out uint pos_i);
uint rand_pcg(inout uint rng_state);
uint hash(uint seed);
int cantor(int a, int b);
Light load_light(int index);
uint wang_hash(inout uint seed);
int hash(ivec3 v);
vec3 sample_random_direction(inout uint state);
int mod(int divident, int divisor);
float RandomFloat01(inout uint state);
ivec3 read(vec3 world_pos, vec3 normal, mat4 mvp, vec3 world_camera_pos);
uint mod(uint divident, uint divisor);
bool RandomBool(inout uint state);
int hash(int seed);
ivec2 reproject(mat4 mvp_matrix, vec3 world_position);
int load_light_offset(vec3 position);
ivec3 write(vec3 world_pos, vec3 normal, mat4 mvp, vec3 world_camera_pos);
Light load_light(int index) {
	index *= light_size;
	vec4 position_full = lights_array[index + 0];
	vec4 color_full = lights_array[index + 1];
	vec4 attenuation_full = lights_array[index + 2];
	return Light(floatBitsToInt(position_full.w), position_full.xyz - world_offset, color_full.xyz, color_full.w, attenuation_full.xy, attenuation_full.z, attenuation_full.w);
}
void get_key(vec3 world_pos, vec3 normal, vec3 world_camera_pos, inout ivec3 key, out uint pos_i) {
	float dist = distance(floor(world_pos), floor(world_camera_pos));
	bool badAngle = dot(normal, normalize(world_pos - world_camera_pos)) > -0.2f && dist > 16.0f;
	float resolution = 0.5f;
	if (dist > 32.0f || badAngle) {
		resolution = 1.0f;
	}
	if (dist > 128.0f) {
		resolution = 2.0f;
	}
	world_pos = floor(world_pos / resolution) * resolution;
	uvec3 pos = uvec3(ivec3(floor(2.0f * world_pos)) & ivec3(511));
	pos_i = pos.x | (pos.y << 9u) | (pos.z << 18u);
	vec3 abs_normal = abs(normal);
	uint n_i = abs_normal.x > abs_normal.y ? 0 : 1;
	n_i = abs_normal[n_i] > abs_normal.z ? n_i : 2;
	n_i += 3 * uint(normal[n_i] > 0);
	pos_i |= n_i << 27;
	uint hash = wang_hash(pos_i);
	key.xy = ivec2(hash >> 16, hash & 0xffffu);
	key.xy %= indirect_res;
}
ivec3 write(vec3 world_pos, vec3 normal, mat4 mvp, vec3 world_camera_pos) {
	ivec3 key = ivec3(0, 0, indirect_write_index);
	uint pos_i = 0;
	get_key(world_pos, normal, world_camera_pos, key, pos_i);
	for (uint i = 0, d = 0; i < 5 && (d = imageAtomicCompSwap(gi_d, key, 0, pos_i).x) != 0 && d != pos_i; i++) {
		key.xy = (key.xy + 1) % indirect_res;
	}
	return key;
}
ivec3 read(vec3 world_pos, vec3 normal, mat4 mvp, vec3 world_camera_pos) {
	ivec3 key = ivec3(0, 0, indirect_read_index);
	uint pos_i = 0;
	get_key(world_pos, normal, world_camera_pos, key, pos_i);
	bool mismatch = false;
	for (uint i = 0, d = 0; i < 5 && (mismatch = (d = imageLoad(gi_d, key).x) != pos_i); i++) {
		key.xy = (key.xy + 1) % indirect_res;
	}
	return !mismatch ? key : ivec3(NULL);
}
ivec2 reproject(mat4 mvp_matrix, vec3 world_position) {
	vec4 viewspace_position = mvp_matrix * vec4(world_position, 1.0f);
	ivec2 pos = ivec2(floor((viewspace_position.xy / viewspace_position.w * 0.5f + 0.5f) * ires));
	return pos % ires;
}
vec2 reprojectf(mat4 mvp_matrix, vec3 world_position, vec2 viewSize, vec2 jitter) {
	vec4 viewspace_position = mvp_matrix * vec4(world_position, 1.0f);
	float w = viewspace_position.w;
	vec2 xy = viewspace_position.xy;
	xy = (xy / w + jitter) * 0.5f + 0.5f;
	return xy * viewSize * 1.0f;
}
int load_light_offset(vec3 position) {
	vec3 o = floor(position / 8.0f);
	return (1 + 20) * int(o.y * 64 * 64 + o.z * 64 + o.x);
}
int mod(int divident, int divisor) {
	return divident - int(divident / divisor) * divisor;
}
uint mod(uint divident, uint divisor) {
	return divident - uint(divident / divisor) * divisor;
}
int hash(ivec3 v) {
	return cantor(hash(v.x), cantor(hash(v.y), hash(v.z)));
}
int cantor(int a, int b) {
	return (a + b + 1) * (a + b) / 2 + b;
}
int hash(int seed) {
	seed = int(seed ^ int(61)) ^ int(seed >> int(16));
	seed *= int(9);
	seed = seed ^ (seed >> 4);
	seed *= int(0x27d4eb2d);
	seed = seed ^ (seed >> 15);
	return seed;
}
uint wang_hash(inout uint seed) {
	seed = uint(seed ^ uint(61)) ^ uint(seed >> uint(16));
	seed *= uint(9);
	seed = seed ^ (seed >> 4);
	seed *= uint(0x27d4eb2d);
	seed = seed ^ (seed >> 15);
	return seed;
}
uint hash(uint seed) {
	seed = uint(seed ^ uint(61)) ^ uint(seed >> uint(16));
	seed *= uint(9);
	seed = seed ^ (seed >> 4);
	seed *= uint(0x27d4eb2d);
	seed = seed ^ (seed >> 15);
	return seed;
}
bool RandomBool(inout uint state) {
	return bool(wang_hash(state) & 1u);
}
uint rand_pcg(inout uint rng_state) {
	uint state = rng_state;
	rng_state = rng_state * 747796405u + 2891336453u;
	uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
	return (word >> 22u) ^ word;
}
float RandomFloat01(inout uint state) {
	uint x = rand_pcg(state);
	state = x;
	return float(x) * uintBitsToFloat(0x2f800000u);
}

vec3 sampleHemisphere(vec2 noise){
    float cosTheta = sqrt(noise.x);
    float sinTheta = sqrt(1.0 - noise.x);

    float phi = 2.0 * 3.1415926 * noise.y;

    return vec3(
        cos(phi) * sinTheta,
        sin(phi) * sinTheta,
        cosTheta
    );
}

mat3 frisvadTBN(vec3 normal){
	mat3 tbn;
	tbn[2] = normal;

	if(normal.z < -0.9) {
			tbn[0] = vec3(0.,-1,0);
			tbn[1] = vec3(-1, 0, 0);
	} else {
			float a = 1./(1.+normal.z);
			float b = -normal.x*normal.y*a;
			tbn[0] = vec3(1. - normal.x*normal.x*a, b, -normal.x) ;
			tbn[1] = vec3(b, 1. - normal.y*normal.y*a , -normal.y);
	}

	return tbn;
}

vec3 sample_random_direction(inout uint state) {
	float z = RandomFloat01(state);
	float a = RandomFloat01(state);
	return sampleHemisphere(vec2(z, a));
}
int to_fake_air_entry(ivec3 pos);
int get_block_id(vec3 pos);
int get_result_sky_light(vec3 normal);
bool is_inside(vec3 position);
int get_block_pointer(vec3 position);
int get_index(ivec3 position);
int get_world_index(ivec3 position);
vec4 unpack_color(int packedColor);
float intersects_world(vec3 direction_inv, vec3 origin);
void trace_ray(inout RayJob job);
void trace_ray(inout RayJob job, bool transparency);
const int[] morton = int[](0, 1, 8, 9, 64, 65, 72, 73, 512, 513, 520, 521, 576, 577, 584, 585, 4096, 4097, 4104, 4105, 4160, 4161, 4168, 4169, 4608, 4609, 4616, 4617, 4672, 4673, 4680, 4681);
const float tint_darken_cutoff = 0.7f;
const float tint_darken_offset = 1.0f - 0.7f;
const float tint_darken_factor = 1.0f / tint_darken_offset;
int RAY_ITERATION_COUNT = 100;
bool ray_iteration_bound_reached = false;
vec3 debug = vec3(0.0f);
int result_block_id = -1;
vec3 result_tint_color = vec3(1.0f);
int ph_result_sky_brightness = 0;
ivec3 ray_target = ivec3(-9999);
ivec3 ray_constraint = ivec3(-9999);
bool breakOnEmpty = false;
vec3 lightEmittance = vec3(0.0f);
void trace_ray(inout RayJob job, bool transparency) {
	job.direction = normalize(job.direction);
	vec3 direction_inv = 1.0f / job.direction;
	float t0 = intersects_world(direction_inv, 16.0f * job.origin);
	if (t0 == -1.0f) {
		job.result_position = vec3(4.7823934E7f) - world_offset;
		return;
	}
	vec3 position = job.origin * 16.0f + (t0 + 0.03f) * job.direction;
	vec3 ray_direction_sign = sign(job.direction);
	int emission_ptr = -1;
	ivec3 intersection_index = ivec3(7.5f * ray_direction_sign + vec3(7.5f, 12.5f, 17.5f));
	vec3 skipDelta = ray_direction_sign * 1.0E-5f;
	ivec3 intersection_offset = max(ivec3(ray_direction_sign), 0);
	int t_min = -1;
	int block_index = -1;
	int voxel_index = 0;
	ivec3 new_index = ivec3(0);
	ivec3 old_index = ivec3(0);
	ivec3 entries = ivec3(0);
	result_tint_color = vec3(1.0f);
	result_block_id = -1;
	ph_result_sky_brightness = 0;
	vec3 previous_tint = vec3(-1.0f);
	for (int i = RAY_ITERATION_COUNT; !(ray_iteration_bound_reached = i < 0); i--) {
		ivec3 w = ivec3(position);
		ivec3 block_position = w >> 4;
		if (!is_inside(position)) return;
		if ((job.result_hit = block_position == ray_target)) {
			break;
		}
		if (ray_constraint != ivec3(-9999) && block_position != ray_constraint) return;
		int scale = 0;
		int entry = 0;
		new_index.x = get_world_index((w >> 8) & 31);
		if (new_index.x != old_index.x) {
			entries.x = root_array[new_index.x];
		}
		if (entries.x < 0) {
			ivec3 block_pos = (w >> 4) & 15;
			new_index.y = -entries.x + get_index(block_pos);
			if (new_index.y != old_index.y) {
				entries.y = cb_array[new_index.y];
				if (entries.y < 0) {
					int block_data = -entries.y;
					block_index = block_data & 0xfff;
					block_index = block_index * (ph_byte_size / 4);
					ph_result_sky_brightness = block_data >> 12;
					result_block_id = cb_array[block_index];
					emission_ptr = block_index + 1;
					voxel_index = block_index + 2;
				}
				else {
					block_index = -1;
				}
			}
			if (block_index != -1) {
				ivec3 voxel_pos = w & 15;
				new_index.z = voxel_index + get_index(voxel_pos);
				if (new_index.z != old_index.z) {
					entries.z = cb_array[new_index.z];
					if (breakOnEmpty && entries.z == 519536640) {
						job.result_hit = true;
						entries.z = -0;
						break;
					}
				}
				if (entries.z < 0) {
					job.result_hit = true;
					break;
				}
				else {
					scale = 0;
					entry = entries.z;
				}
			}
			else {
				scale = 4;
				entry = entries.y;
			}
		}
		else {
			scale = 8;
			entry = entries.x;
		}
		old_index = new_index;
		ivec3 intersection = (((ivec3(entry) >> intersection_index) & 31) + intersection_offset) << scale;
		scale += 4;
		scale += int(scale == 8 + 4);
		intersection += w & (-1 << scale);
		vec3 t = (intersection - position) * direction_inv;
		t_min = int(t.x >= t.y);
		t_min = t.z < t[t_min] ? 2 : t_min;
		position += t[t_min] * job.direction;
		position[t_min] = (intersection[t_min] * 0.01f + skipDelta[t_min]) * 100.0f;
	}
	if (job.result_hit) {
		lightEmittance = unpackUnorm4x8(cb_array[emission_ptr]).xyz;
	} else {
		lightEmittance = vec3(0.0f);
	}
	job.result_color = vec3((-entries.z >> 0) & 0xff, (-entries.z >> 8) & 0xff, (-entries.z >> 16) & 0xff) / 0xff;
	job.result_position = job.result_hit ? vec3(position / 16.0f) : (vec3(4.7823934E7f) - world_offset);
	if (t_min != -1) job.result_normal[t_min] = sign(-ray_direction_sign[t_min]);
	ray_target = ivec3(-1);
}
void trace_ray(inout RayJob job) {
	trace_ray(job, false);
}
int get_block_pointer(vec3 position) {
	if (!is_inside(16.0f * position)) {
		return -1;
	}
	ivec3 w = ivec3(position);
	int index = 0;
	index = root_array[get_world_index((w >> 4) & 31)];
	if (index >= 0) return -1;
	index = cb_array[-index + get_index(w & 15)];
	if (index >= 0) return -1;
	return (-index & 0xfff) * (ph_byte_size / 4);
}
int get_block_id(vec3 pos) {
	int ptr = get_block_pointer(pos);
	if (ptr == -1) {
		return -1;
	}
	return cb_array[ptr];
}
float intersects_world(vec3 direction_inv, vec3 origin) {
	if (is_inside(origin)) {
		return 0.0f;
	}
	vec3 tbot = direction_inv * (world_min_voxel - origin);
	vec3 ttop = direction_inv * (world_max_voxel - origin);
	vec3 tmin = min(ttop, tbot);
	vec3 tmax = max(ttop, tbot);
	vec2 t = max(tmin.xx, tmin.yz);
	float t0 = max(t.x, t.y);
	t = min(tmax.xx, tmax.yz);
	float t1 = min(t.x, t.y);
	return t1 > max(t0, 0.0f) ? t0 : -1.0f;
}
bool is_inside(vec3 position) {
	vec3 s = step(world_min_voxel, position) - step(world_max_voxel, position);
	return bool(s.x * s.y * s.z);
}
int get_index(ivec3 position) {
	return morton[position.x] | (morton[position.y] << 1) | (morton[position.z] << 2);
}
int get_world_index(ivec3 position) {
	return morton[position.x] | (morton[position.y] << 1) | (morton[position.z] << 2);
}
int get_result_sky_light(vec3 normal) {
	int index = clamp(int(abs(normal.x) * (normal.x * 0.5f + 0.5f) + abs(normal.y) * (normal.y * 0.5f + 2.5f) + abs(normal.z) * (normal.z * 0.5f + 4.5f) + 0.5f), 0, 5);
	int level = (ph_result_sky_brightness >> (index * 3)) & 0x7;
	return int((level / 7.0f) * 15.0f);
}
vec4 unpack_color(int packedColor) {
	vec3 rgb = vec3((packedColor >> 0) & 0xff, (packedColor >> 8) & 0xff, (packedColor >> 16) & 0xff) / 255.0f;
	return vec4(rgb, (127 - (packedColor >> 24)) / 127.0f);
}
int to_fake_air_entry(ivec3 pos) {
	int value = (pos.x << 0) | (pos.y << 5) | (pos.z << 10);
	return value | (value << 15);
}

#include "/photonics/shader_interface.glsl"
uniform sampler2D skyViewLUTTex;
uniform float far;
uniform vec3 worldMoonDir;
uniform sampler2D moontex;
uniform sampler2D sunTransmittanceLUTTex;
uniform vec3 worldSunDir;
#include "/lib/atmosphere/sky.glsl"

float signed_nudge(float value) {
	if (value <= 0.0f) return min(value, -0.001f);
	else if (value >= 0) return max(value, 0.001f);
	else return value;
}
vec3 ph_sun_direction = vec3(signed_nudge(worldLightDir.x), signed_nudge(worldLightDir.y), signed_nudge(worldLightDir.z));
ivec2 gBufferLoc = ivec2(gl_FragCoord.xy);
uint rngState = uint(uint(gl_FragCoord.x) * uint(1973) + uint(gl_FragCoord.y) * uint(9277) + uint(frameCounter) * uint(26699)) | uint(1);
vec4 texelFetch0(sampler2D sampler, ivec2 pos, int level);
void process_direct(inout Frag frag, int light_offset, int light_count, int soft_light_count);
void sample_light_direction(inout Light light, float light_radius);
float g(float x);
void process_indirect();
float h(float x);
Frag mixNullable4(Frag s1, Frag s2, float a);
void main(void);
float n(float x);
float signed_nudge(float value);
vec3 sample_direct_lighting(vec3 position, vec3 normal, vec3 mapped_normal, Light light);
float ph_luminance(vec3 rgb);
vec3 sample_indirect_lighting();
Frag get(vec2 uv);
Frag get_mixed(vec2 center);
float blue_noise(int index);
void reproject(bool sample_indirect);
RayJob light_ray = RayJob(vec3(0), vec3(0), vec3(0), vec3(0), vec3(0), false);
vec3 base_position = vec3(0.0f);
vec3 base_normal = vec3(0.0f);
vec3 mapped_normal = vec3(0.0f);
void main(void) {
	if (!is_in_world()) {
		return;
	}
	vec3 albedo = vec3(0.0f);
	load_fragment_variables(albedo, base_position, base_normal, mapped_normal);
	base_position -= world_offset;
	handheld_frag_out = vec4(0.0f);
	reproject(true);
	if (any(notEqual(handheld_color, vec3(0.0f)))) {
		vec4 direction_vert_out = direction_transformation_matrix_in * vec4(left_handed ? 1.0f : -1.0f, -1.0f, 0.0f, 1.0f);
		direction_vert_out.w = 1.0f / direction_vert_out.w;
		direction_vert_out.xyz *= direction_vert_out.w;
		light_ray.origin = direction_vert_out.xyz + eyePosition - world_offset;
		vec3 to_light = base_position - light_ray.origin;
		light_ray.direction = normalize(to_light);
		trace_ray(light_ray);
		float distance_squared = dot(to_light, to_light);
		float brightness = 2.1f / dot(vec2(1, distance_squared), vec2(0.9f, 0.1f));
		brightness = max(brightness, 0.02f);
		float hand_to_base_distance = distance(light_ray.origin, base_position);
		float hand_to_result_distance = distance(light_ray.origin, light_ray.result_position);
		brightness *= clamp(30.0f * (hand_to_result_distance - hand_to_base_distance + 0.05f), 0.0f, 1.0f);
		brightness *= dot(mapped_normal, -light_ray.direction);
		brightness *= (h(frameCounter / 300.0f) * 0.1f + h(frameCounter / 100.0f) * 0.05f) + 0.4f;
		handheld_frag_out.xyz = brightness * handheld_color;
	}
	else {
		handheld_frag_out.xyz = vec3(0.0f);
	}
	handheld_frag_out.w = 1.0f;
}
const float F = 2.0f;
float g(float x) {
	return sin(F * 3.141592f * clamp(x, 0.0f, 1.0f / F));
}
float n(float x) {
	return 0.5f * sin(1000.0f * x) + 0.5f;
}
float h(float x) {
	return g(fract(x) - (1.0f - 1.0f / F) * n(floor(x)));
}
float ph_luminance(vec3 rgb) {
	return dot(rgb, vec3(0.2126f, 0.7152f, 0.0722f));
}
const Frag NULL4 = Frag(vec4(-999), vec4(-999));
vec4 texelFetch0(sampler2D sampler, ivec2 pos, int level) {
	return texelFetch(sampler, pos, level);
}
Frag get(vec2 uv) {
	vec3 d = texelFetch0(prev_radiosity_position, ivec2(uv), 0).xyz - base_position - world_offset;
	if (dot(d, d) >= 0.1f) {
		return NULL4;
	}
	vec3 n = texelFetch0(prev_radiosity_normal, ivec2(uv), 0).xyz;
	if (dot(n, base_normal) < 0.99f) {
		return NULL4;
	}
	vec4 direct = texelFetch0(prev_radiosity_direct, ivec2(uv), 0);
	vec4 direct_soft = texelFetch0(prev_radiosity_direct_soft, ivec2(uv), 0);
	return Frag(direct, direct_soft);
}
Frag get_mixed(vec2 center) {
	ivec2 icenter = ivec2(center);
	Frag c_00 = get(icenter + ivec2(0, 0));
	Frag c_10 = get(icenter + ivec2(1, 0));
	Frag c_01 = get(icenter + ivec2(0, 1));
	Frag c_11 = get(icenter + ivec2(1, 1));
	Frag frag = mixNullable4(mixNullable4(c_00, c_10, fract(center.x)), mixNullable4(c_01, c_11, fract(center.x)), fract(center.y));
	return frag;
}
Frag mixNullable4(Frag s1, Frag s2, float a) {
	if (s1 == NULL4) {
		a = 1.0f;
	} else if (s2 == NULL4) {
		a = 0.0f;
	}
	vec4 direct = mix(s1.direct, s2.direct, a);
	vec4 direct_soft = mix(s1.direct_soft, s2.direct_soft, a);
	return Frag(direct, direct_soft);
}
void reproject(bool sample_indirect) {
	vec2 center = reprojectf(previous_modelview_projection, base_position + world_offset + 0.01f * base_normal, vec2(viewWidth, viewHeight), get_taa_jitter());
	position_frag_out = vec4(base_position + world_offset, 1.0f);
	normal_frag_out = vec4(base_normal, 1.0f);
	center -= 0.5f;
	Frag frag = get_mixed(center);
	if (frag == NULL4 || RandomFloat01(rngState) > 0.995f) {
		frag.direct = vec4(0.0f);
		frag.direct_soft = vec4(0.0f);
	}
	int light_offset = load_light_offset(base_position);
	int light_count = light_registry_array[light_offset];
	int soft_light_count = min(3, light_count);
	process_direct(frag, light_offset, light_count, soft_light_count);
	ivec3 inside = ivec3(lessThan(abs(fract(base_position) - 0.5f), vec3(0.48f)));
	bool onEdge = inside.x + inside.y + inside.z <= 1;
	if (!onEdge) {
		process_indirect();
	}
	frag.direct.w = max(frag.direct.w, 0.01f);
	direct_frag_out = frag.direct;
	frag.direct_soft.w = max(frag.direct_soft.w, 0.01f);
	direct_soft_frag_out = frag.direct_soft;
}
void process_direct(inout Frag frag, int light_offset, int light_count, int soft_light_count) {
	for ( ; frag.direct.w < light_count - soft_light_count; frag.direct.w++) {
		int index = light_registry_array[soft_light_count + int(frag.direct.w) + light_offset + 1];
		Light light = load_light(index);
		frag.direct.xyz += sample_direct_lighting(base_position, base_normal, mapped_normal, light);
	}
	for (int i = 0; i < soft_light_count; i++) {
		int index = light_registry_array[(int(frag.direct_soft.w) % soft_light_count) + light_offset + 1];
		Light light = load_light(index);
		sample_light_direction(light, 1.0f / 16.0f);
		frag.direct_soft.xyz += soft_light_count * sample_direct_lighting(base_position, base_normal, mapped_normal, light);
		frag.direct_soft.w++;
	}
}
void process_indirect() {
	vec3 sample_position = base_position + world_offset;
	ivec3 write = write(sample_position, base_normal, modelview_projection, world_camera_position);
	uint w = imageAtomicAdd(gi_w, write, uint(1));
	if (w == 0) {
		ivec3 read = read(sample_position, base_normal, previous_modelview_projection, previous_world_camera_position);
		vec4 result = vec4(0.0f);
		result.x += imageLoad(gi_x, read).x / 255.0f;
		result.y += imageLoad(gi_y, read).x / 255.0f;
		result.z += imageLoad(gi_z, read).x / 255.0f;
		result.w = imageLoad(gi_w, read).x;
		result *= 0.975f;
		imageAtomicAdd(gi_x, write, uint(result.x * 255.0f));
		imageAtomicAdd(gi_y, write, uint(result.y * 255.0f));
		imageAtomicAdd(gi_z, write, uint(result.z * 255.0f));
		imageAtomicAdd(gi_w, write, uint(result.w));
	}
	else if (w < 2048) {
		vec3 result = sample_indirect_lighting();
		imageAtomicAdd(gi_x, write, uint(result.x * 255.0f));
		imageAtomicAdd(gi_y, write, uint(result.y * 255.0f));
		imageAtomicAdd(gi_z, write, uint(result.z * 255.0f));
	}
	else {
		imageAtomicAdd(gi_w, write, uint(-1));
	}
}
vec3 sample_indirect_lighting() {
	light_ray.result_position = base_position;
	light_ray.result_normal = base_normal;
  light_ray.origin = light_ray.result_position + 0.1f * light_ray.result_normal;
  mat3 tbn = frisvadTBN(light_ray.result_normal);
  light_ray.direction = normalize(tbn * sample_random_direction(rngState));
  RAY_ITERATION_COUNT = 20;
  breakOnEmpty = true;
  trace_ray(light_ray, true);
  breakOnEmpty = false;
  RAY_ITERATION_COUNT = 100;

  if (!light_ray.result_hit) {
    return getSky(light_ray.direction, false);
  }
  else {
    vec3 sample_albedo = light_ray.result_color;
    vec3 sample_normal = light_ray.result_normal;
    if(dot(sample_normal, worldLightDir) < 0.0){
      return vec3(0.0);
    }
    light_ray.direction = worldLightDir;
    light_ray.origin = light_ray.result_position + 0.1f * light_ray.result_normal;
    RAY_ITERATION_COUNT = 20;
    breakOnEmpty = true;
    trace_ray(light_ray, true);
    breakOnEmpty = false;
    RAY_ITERATION_COUNT = 100;
    if (!light_ray.result_hit && !ray_iteration_bound_reached) {
      return sample_albedo * sunlightColor * max(0.0, dot(sample_normal, worldLightDir));
    } else {
      return vec3(0.0);
    }
  }
}
float blue_noise(int index) {
	return texelFetch0(noisetex, ivec2(rand_pcg(rngState), rand_pcg(rngState)) & 511, 0).b;
}
void sample_light_direction(inout Light light, float light_radius) {
	vec3 light_position = floor(light.position) + 0.5f;
	vec2 rnd_sample = vec2(blue_noise(0), blue_noise(1));
	vec3 light_dir = light_position - light_ray.origin;
	vec3 light_tangent = normalize(cross(light_dir, normalize(vec3(0.0f, 1.0f, 1.0f))));
	vec3 light_bitangent = normalize(cross(light_tangent, light_dir));
	float point_radius = light_radius * sqrt(rnd_sample.x);
	float point_angle = rnd_sample.y * 2.0f * 3.14159265f;
	vec2 disk_point = vec2(point_radius * cos(point_angle), point_radius * sin(point_angle));
	light.position = light_position + disk_point.x * light_tangent + disk_point.y * light_bitangent;
}
vec3 sample_direct_lighting(vec3 position, vec3 normal, vec3 mapped_normal, Light light) {
	light_ray.origin = position + normal * 0.02f;
	vec3 to_light = light.position - light_ray.origin;
	light_ray.direction = normalize(to_light);
	float distance_squared = dot(to_light, to_light) * light.falloff;
	light.color /= dot(vec2(1, distance_squared), light.attenuation);
	if (floor(light.position) == floor(position)) {
		return light.color;
	}
	if (dot(light_ray.direction, mapped_normal) <= 0.01f) {
		return vec3(0.0f);
	}
	float cosine = clamp(dot(mapped_normal, light_ray.direction) * 2.0f, 0.0f, 1.0f);
	light.color *= cosine;
	if (ph_luminance(light.color) < 0.001f) {
		return vec3(0.0f);
	}
	ray_target = ivec3(light.position);
	RAY_ITERATION_COUNT = 20;
	trace_ray(light_ray, true);
	RAY_ITERATION_COUNT = 100;
	if (!light_ray.result_hit && light.attenuation.y == 0.0f) {
		light.color = vec3(0.0f);
	}
	if (floor(light.position) != floor(light_ray.result_position)) {
		light.color = vec3(0.0f);
	}
	light.color *= result_tint_color;
	return light.color;
}
